
  - name: Yum Update
    yum: name=* state=latest

  - name: Yum Install
    yum: name={{ item }} state=latest
    with_items:
      - vim
      - unzip
      - ntp
      - wget
      - tree
      - net-tools
      - epel-release
#      - inotify-tools
      - ipa-gothic-fonts
      - ipa-mincho-fonts
      - ipa-pgothic-fonts
      - ipa-pmincho-fonts

  - name: SELINUX無効
    replace: >-
      dest=/etc/sysconfig/selinux
      regexp='SELIUX=permissive'
      replace='SELINUX=disabled'
      backup=yes

  - name: ntpd起動
    service: name={{ item }} enabled=yes state=started
    with_items:
      - ntpd

  - name: Firewalld 設定 
    firewalld: service={{ item }} permanent=true state=enabled immediate=true
    with_items:
      - ntp

  - name: 作業フォルダ作成
    file: path=/work state=directory
