  - name: httpd インストール
    yum: name=httpd state=latest

  - stat: path=/etc/httpd/conf.d/userdir.conf
    register: stat
  - shell: mv -f /etc/httpd/conf.d/userdir.conf /etc/httpd/conf.d/userdir.back
    when: stat.stat.exists

  - stat: path=/etc/httpd/conf.d/welcome.conf
    register: stat
  - shell: mv -f /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.back 
    when: stat.stat.exists

  - stat: path=/etc/httpd/conf.d/autoindex.conf
    register: stat
  - shell: mv -f /etc/httpd/conf.d/autoindex.conf /etc/httpd/conf.d/autoindex.back
    when: stat.stat.exists

  - name: httpd 起動
    service: name=httpd enabled=yes state=started

  - name: Firewall 設定
    firewalld: service={{ item }} permanent=true state=enabled immediate=true
    with_items:
      - http
      - https
