
  - name: Repo install
    yum: name={{ item }} state=latest
    with_items:
      - http://ftp.iij.ad.jp/pub/linux/fedora/epel/7/x86_64/e/epel-release-7-10.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

  - name: php56 install
    yum: name={{ item }} enablerepo=remi-php state=latest
    with_items:
      - php
      - php-devel
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd





