# Module: Windows Module
# http://docs.ansible.com/ansible/latest/list_of_windows_modules.html
#
- hosts: windows

  vars:

  tasks:
    - name: Windows Update
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
#          - UpdateRollups
        state: searched
        log_path: c:\ansible_wu.txt

#    - name: Windows Reboot
#      win_reboot:
#        shutdown_timeout_sec: 10
#        reboot_timeout_sec: 10

    - name: Firewall Rule
      action: win_firewall_rule
      args:
        name: https
        enable: yes
        state: present
        localport: 443
        action: allow
        direction: In
        protocol: TCP
