  - name: Yumアップデート
    yum: name=* state=latest
    yum: name={{ item }} state=latest
    with_items:
      - vim
      - wget
      - tree
      - net-tools
      - epel-release

  - name: SELINUX無効
    shell: sed -i "s/\(^SELINUX=\).*/\1disabled/" /etc/selinux/config

  - name: 作業フォルダ作成
    file: path=/work state=directory
