- hosts: all
  remote_user: root
  sudo: yes

  vars:
    jenkins_port: 3001
    jenkins_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    jenkins_key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

  tasks:
  - name: jenkinsインストール
    yum: name=ansible  state=latest
