- hosts: all
  remote_user: root
  sudo: yes

  vars:
    jenkins_port: 3001
    jenkins_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    jenkins_key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

  tasks:
  - name: Yumインストール
    yum: name={{ item }} state=latest
    with_items:
      - java

  - name: リポジトリ追加
    shell: wget -O /etc/yum.repos.d/jenkins.repo {{ jenkins_url }}

  - name: Keyインポート
    shell: rpm --import {{ jenkins_key }}

  - name: jenkinsインストール
    yum: name=jenkins  state=latest

  - name: Port変更
    shell: sed -i "s/\(^JENKINS_PORT=\).*/\1"{{ jenkins_port }}"/" /etc/sysconfig/jenkins

  - name: jenkins起動
    service: name=jenkins state=started

  - name: jenkins自動起動
    service: name=jenkins enabled=yes

  - name: Firewalld設定
    shell: firewall-cmd --zone=public --add-port=3001/tcp --permanent

  - name: Firewalldリロード
    shell: firewall-cmd --reload
