- hosts: all
  remote_user: root
  sudo: yes

  vars:

  tasks:
  - name: 前処理
    include: tasks/base.yml

  - name: Yumインストール
    yum: name={{ item }} state=latest
    with_items:
      - java
      - rsyslog
      - vim-common
      - unzip

  - name: リポジトリインストール
    yum: name="http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm" 

  - name: Zabbixインストール
    yum: name={{ item }} state=latest
    with_items:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-web-japanese
      - zabbix-agent

  - name: Firewalld設定
    firewalld: port=10050 permanent=true state=enabled immediate=true
    firewalld: port=10051 permanent=true state=enabled immediate=true
