- hosts: all
  remote_user: root
  sudo: yes

  vars:
    hinemos_hostname: mgrsrv
    hinemos_manager_url: https://github.com/hinemos/hinemos/releases/download/v6.0.1/hinemos-6.0-manager-6.0.1-1.el7.x86_64.rpm
    hinemos_web_url: https://github.com/hinemos/hinemos/releases/download/v6.0.1/hinemos-6.0-web-6.0.1-1.el7.x86_64.rpm

  tasks:
  - name: 前処理
    include: tasks/base.yml

  - name: Yumインストール
    yum: name={{ item }} state=latest
    with_items:
      - java
      - rsyslog
      - vim-common
      - unzip

  - name: Hostname変更
    shell: hostnamectl set-hostname {{ hinemos_hostname }}

  - name: Hinemos Manager/Web Install
    yum: name={{ item }}
    when_items:
      - {{ hinemos_manager_url }}
      - {{ hinemos_web_url }}

  - name: Hinemos Manager/Web 起動
    service: name={{ item }} enabled=yes state=started
    with_items:
      - hinemos_manager
      - hinemos_web

  - name: Firewalld設定
    firewalld: service={{ item }} permanent=true state=enabled immediate=true
    when_items:
      - http
