- hosts: all
  remote_user: root
  sudo: yes

  vars:

  tasks:
  - name: 前処理
    include: tasks/base.yml

  - name: Yumインストール
    yum: name={{ item }} state=latest
    with_items:
      - java

  - name: Firewalld 設定
    firewalld: port=8080 permanent=true state=enabled immediate=true
