- hosts: all
  remote_user: root
  tasks:
  - name: 前処理
    include: tasks/base.yml

  - name: GNOME Desktopインストール
    yum: name="@GNOME Desktop" state=latest

  - name: GNOME自動起動
    shell: systemctl set-default graphical.target

  - name: xrdp インストール
    yum: name="{{ item }}" state=latest
    with_items:
      - rdesktop
      - xrdp

  - name: xrdp 起動
    service: name=xrdp enabled=yes state=started

  - name: Firewalld設定
    firewalld: port=3389 permanent=true state=enabled immediate=true

  - name: nux-desktopリポジトリ追加
    yum: name="http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm"

  - name: etc. インストール
    yum: name="{{ item }}" state=latest
    with_items:
      - wine
      - kdepim
      - cairo-dock
