- hosts: centos
  remote_user: root
  sudo: yes

  vars:

  tasks:
  - name: 前処理
    include: tasks/base.yml

  - name: key Import
    shell: rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"

  - name: monoリポジトリ追加
    shell: yum-config-manager --add-repo http://download.mono-project.com/repo/centos/

  - name: mono インストール
    yum: name={{ item }} state=latest
    with_items:
      - mono-complete

