- hosts: all
  remote_user: root
  sudo: yes

  vars:

  tasks:
  - name: 前処理
    include: tasks/base.yml

  - name: Yumインストール
    yum: name={{ item }} state=latest
    with_items:
      - bzip2

  - name: リポジトリ追加
    shell: wget -q -O - http://www.atomicorp.com/installers/atomic |sh

  - name: openvasインストール
    yum: name={{ item }}  state=latest
    with_items:
      - openvas

  - name: openvasセットアップ
    shell: openvas-setup

  - name: SSL証明書作成
    shell: openvas-mkcert-client -n om -i

  - name: OpenVAS Manager Rebuild
    shell: openvasmd --rebuild

  - name: Firewalld設定
    firewalld: port={{ item }} permanent=true state=enabled immediate=true
    with_items:
      - 9392

