- hosts: centos
  remote_user: root
  sudo: yes

  vars:

  tasks:
  - name: 前処理
    include: tasks/base.yml

  - name: owncloud/mariadb インストール
    yum: name={{ item }} state=latest
    with_items:
      - owncloud
      - mariadb-server

  - name: replace /etc/httpd/conf.d/owncloud.conf
    replace: dest=/etc/httpd/conf.d/owncloud.conf regexp='^local$' replace='any' backup=yes

  - name: mariadb 起動
    service: name={{ item }} enabled=yes state=started
    with_items:
      - mariadb

  - name: httpd 再起動
    service: name={{ item }} enabled=yes state=restarted
    with_items:
      - httpd


