- hosts: centos
  remote_user: root
  sudo: yes

  vars:
    install_name: TestLink
    alias_name: testlink
    download_url: https://ja.wordpress.org/wordpress-4.8-ja.zip

  tasks:
  - name: 前処理
    include: tasks/base.yml

  - name: LAMP Install
    include: tasks/lamp.yml

  - name: Prodict Install
    get_url: url={{ download_url }} dest=/work

  - name: Product 解凍
    unarchive: src=/work/wordpress-4.8-ja.zip dest=/opt

  - name: Product パーミッション
    file: path=/opt/wordpress owner=apache group=apache recurse=yes state=directory

  - name: Product Alias Copy
    template: src=/opt/playbook/alias.conf dest=/etc/httpd/conf.d/{{ alias_name }}.conf

  - name: Product Alias Replace
    replace: >-
      dest=/etc/httpd/conf.d/{{ alias_name }}.conf
      regexp='change'
      replace='{{ alias_name }}'

  - name: httpd 再起動
    service: name={{ item }} enabled=yes state=restarted
    with_items:
      - httpd


